
spring:
  datasource:
#    #얘는 컨테이너 안에서 접속할때의 url임
#    url: jdbc:mysql://mymymysql:3308do/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: testuser
#    password: testpass
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 10
  #이번에는 h2를 쓸거라고
    #h2 db의 연결 위치와 접속방법
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
      #h2db에 대한 위치
  h2:
    console:
        enabled: true
        path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      jdbc.time_zone: Asia/Seoul
server:
  port: 8080
