spring:
  datasource:
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    #h2db에 대한 위치
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      jdbc.time_zone: Asia/Seoul

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - loggers
          - threaddump
          - prometheus # 추가

  endpoint:
    health:
      show-details: ALWAYS
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

  info:
    env:
      enabled: true

# 별도 포트를 사용하려면 주석 해제 후 필요한 포트로 설정
#  server:
#    port: 8081

info:
  app:
    name: "마이 스프링 부트 어플리케이샨이다 이말이야"
    version: "1.0.0"
  team: "끼얏호우"
server:
  port: 8080
